FROM  alpine:3.19.0

RUN <<EOF
    apk add --no-cache nodejs
    apk add --no-cache npm
    apk add --no-cache git
    apk add --no-cache nano
    apk add --no-cache unzip
EOF

#Adiciona um usuário no SO (Linux distro Alpine)
RUN adduser -D ricardo \
    && addgroup infra \
    && addgroup ricardo infra

#Define o usuário responsável pela execução dos RUNs
USER ricardo

#ADD ./arquivo_abc.txt /tmp/
#ADD ./arquivo_xyz.txt /tmp/
#ADD --chown=ricardo:infra --chmod=777 ./arquivo_123.txt /tmp/

#ADD --chown=ricardo:infra ./arquivo_*.txt /tmp/ -> dessa forma ele irá copiar todos os arquivos iniciados
#com o nome arquivo
#ADD --chown=ricardo:infra --chmod=777 ./arquivo_ab?.??? /tmp/ -> a (?) substitui um caracter

ADD --chown=ricardo:infra arquivos.zip /tmp/arquivos/

RUN cd /tmp/arquivos/ \
    && unzip arquivos.zip